#!/bin/bash

# Errors handling
set -e
set -o pipefail  # Also catch errors in piped commands
trap 'echo "ERROR: Script failed at line $LINENO. Command: $BASH_COMMAND" && exit 1' ERR

# Ensure script is run with root privileges
if [ "$EUID" -ne 0 ]; then
   echo "Please run this script with root privileges"
   exit 1
fi

cat << 'EOF'
 _   _           _        ____                                       
| \ | | ___   __| | ___  / ___| _ __   __ ___      ___ __   ___ _ __ 
|  \| |/ _ \ / _` |/ _ \ \___ \| '_ \ / _` \ \ /\ / / '_ \ / _ \ '__|
| |\  | (_) | (_| |  __/  ___) | |_) | (_| |\ V  V /| | | |  __/ |   
|_| \_|\___/ \__,_|\___| |____/| .__/ \__,_| \_/\_/ |_| |_|\___|_|   
                               |_|                                   

 Node Spawner v1.0 - Spawn nodes of all kind - github.com/alexandre-pecorilla/NodeSpawner

EOF


echo -e "This script will install and deploy a fully operational Tor Middle/Guard relay on your server.\nUse it on a fresh VPS running recent versions of Debian or Ubuntu.\n" 
read -p "Press enter to spawn your relay..."

echo -e "\n\n=========================================\nStep 0: Fetch system info...\n=========================================\n\n"
arch=$(dpkg --print-architecture)
echo "Architecture: $arch"
dist=$(lsb_release -cs)
echo "Distribution code name: $dist"

echo -e "\n=========================================\nStep 1: Add Tor repository & GPG key...\n=========================================\n\n"
cat > /etc/apt/sources.list.d/tor.list << EOF
deb     [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org $dist main
deb-src [signed-by=/usr/share/keyrings/deb.torproject.org-keyring.gpg] https://deb.torproject.org/torproject.org $dist main
EOF
wget -qO- https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --dearmor | tee /usr/share/keyrings/deb.torproject.org-keyring.gpg >/dev/null
echo -e "SUCCESS: Repository and GPG key added.\n"

echo -e "\n=========================================\nStep 2: Install APT packages...\n=========================================\n\n"
apt update > /dev/null 2>&1
apt install -y apt-transport-https gnupg ufw tor > /dev/null 2>&1
echo -e "SUCCESS: Packages installed.\n"

echo -e "\n=========================================\nStep 3: Collect relay info...\n=========================================\n\n"

# Prompt for relay name
while true; do
  read -rp "Pick a name for your relay (use only letters and digits / no spaces or special characters): " relay_name
  # Allow only alphanumerics
  if [[ -z "$relay_name" ]]; then
    echo "Relay name cannot be empty."
  elif [[ "$relay_name" =~ ^[a-zA-Z0-9]+$ ]]; then
    break
  else
    echo "Invalid relay name. Use only letters and digits (no spaces or special characters)."
  fi
done

# Prompt for email address
while true; do
  read -rp "Enter your email address (be aware it will be published): " email_address
  # Simple email regex
  if [[ -z "$email_address" ]]; then
    echo "Email cannot be empty."
  elif [[ "$email_address" =~ ^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$ ]]; then
    break
  else
    echo "Invalid email address."
  fi
done

# Prompt for port number
while true; do
  read -rp "Enter the relay ORPort (default 443): " port_number
  if [[ -z "$port_number" ]]; then
    port_number=443
    break
  elif [[ "$port_number" =~ ^[0-9]+$ ]] && (( port_number >= 1 && port_number <= 65535 )); then
    break
  else
    echo "Invalid port number."
  fi
done

echo -e "\nSUCCESS: Relay info collected.\n"

echo -e "\n=========================================\nStep 4: Configure relay...\n=========================================\n\n"
systemctl stop tor

# Remove any previous autogenerated relay block
sed -i '/^# BEGIN AUTOGENERATED TOR RELAY CONFIG$/,/^# END AUTOGENERATED TOR RELAY CONFIG$/d' /etc/tor/torrc

# Append new relay config cleanly
tee -a /etc/tor/torrc >/dev/null <<EOF

# BEGIN AUTOGENERATED TOR RELAY CONFIG
Nickname $relay_name
ContactInfo $email_address
ORPort $port_number
ExitRelay 0
SocksPort 0
# END AUTOGENERATED TOR RELAY CONFIG
EOF

echo -e "SUCCESS: Relay configured.\n"

echo -e "\n=========================================\nStep 5: Setup firewall...\n=========================================\n\n"

while true; do
  read -rp "Enter your SSH port (e.g., 22) to avoid being locked out: " ssh_port
  if [[ "$ssh_port" =~ ^[0-9]+$ ]] && (( ssh_port >= 1 && ssh_port <= 65535 )); then
    break
  else
    echo "Invalid SSH port. Must be between 1 and 65535."
  fi
done

ufw allow $ssh_port/tcp > /dev/null 2>&1
ufw allow $port_number/tcp > /dev/null 2>&1
ufw --force enable > /dev/null 2>&1
ufw status

echo -e "SUCCESS: Firewall enabled.\n"


echo -e "\n=========================================\nStep 6: Spawn relay...\n=========================================\n\n"
systemctl restart tor
echo -e "SUCCESS: Relay started.\n"

sleep 10 # Wait for Tor to write its fingerprint
fingerprint_file="/var/lib/tor/fingerprint"

if [[ ! -f "$fingerprint_file" ]]; then
  echo "Waiting 60 seconds for Tor to generate the relay fingerprint..."
  sleep 60
fi

# Extract fingerprint
if [[ -f "$fingerprint_file" ]]; then
  fingerprint=$(awk '{print $2}' "$fingerprint_file")
  echo "Your relay is up and running!"
  echo "Relay fingerprint => $fingerprint"
  echo "Relay Search page (wait a few hours for it to appear): => http://hctxrvjzfpvmzh2jllqhgvvkoepxb4kfzdjm6h7egcwlumggtktiftid.onion/rs.html#details/$fingerprint"
else
  echo "Fingerprint file not found. Something must have gone wrong."
fi

